version: "3.7"
services:
  apache:
    build: ./bin/apache/
    container_name: "${APP_NAME}_apache"
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "${API_PORT}:80"
    volumes:
      - ./www/:/app
  php:
    build: ./bin/php
    container_name: "${APP_NAME}_php"
    restart: always
    networks:
      - backend
    volumes:
      - ./www:/app
      - ./bin/php/php.ini:/usr/local/etc/php/php.ini
  mysql:
    build: ./bin/mysql
    container_name: "${APP_NAME}_mysql"
    restart: always
    environment:
      MYSQL_USER: restapi
      MYSQL_PASSWORD: restapi
      MYSQL_DATABASE: restapi
      MYSQL_ROOT_PASSWORD: restapi
    networks:
      - backend
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  redis:
    build: ./bin/redis
    container_name: '${APP_NAME}_redis'
    sysctls:
      net.core.somaxconn: 1024
    networks:
      - backend
    ports:
      - "6379:6379"
networks:
  frontend:
    name: "${APP_NAME}_frontend"
  backend:
    name: "${APP_NAME}_backend"